name: Bug Report
description: Report a bug or issue with MCPLI
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue with MCPLI!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A concise description of the issue you’re experiencing.
      placeholder: When trying to run a tool via MCPLI...
    validations:
      required: true

  - type: input
    id: mcpli-version
    attributes:
      label: MCPLI Version
      description: Output of `mcpli --version` or the commit SHA you’re using
      placeholder: 1.0.0 or abcdef12
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: v22.6.0
    validations:
      required: true

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: 15.5 (arm64)
    validations:
      required: true

  - type: textarea
    id: commands
    attributes:
      label: Commands Run
      description: Paste the exact MCPLI command(s) you ran, including the MCP server command after `--`.
      placeholder: |
        $ mcpli get-weather --location "London" -- node weather-server.js
        $ mcpli --debug get-weather --location "London" -- node weather-server.js
      render: shell
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Exact command you ran
        2. What you expected to happen
        3. What actually happened
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment Variables (if any)
      description: List any env vars you set before running MCPLI
      placeholder: |
        MCPLI_DEFAULT_TIMEOUT=600
        API_KEY=...
      render: shell
    validations:
      required: false

  - type: textarea
    id: daemon-status
    attributes:
      label: Daemon Status (optional)
      description: Output of `mcpli daemon status`
      render: shell
    validations:
      required: false

  - type: textarea
    id: debug-logs
    attributes:
      label: Debug Logs (optional)
      description: Run the failing command with `--debug` and paste relevant excerpt
      render: shell
    validations:
      required: false
