name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Type check
      run: npm run typecheck

    - name: Run tests (macOS launchd + unit/integration/e2e)
      run: npm test

    - name: Publish PR package (pkg-pr-new)
      if: github.event_name == 'pull_request' && matrix.node-version == '22.x'
      run: npx pkg-pr-new publish
